Lab5 (two projects)
De-Len/3_Semester_Android_Kotlin pull request #5
Opened 2024-10-31 16:22 UTC by De-Len

Projects:
GSON
MyDialer

2024-11-05 05:37 UTC, Alexey-GM requested changes

2024-11-05 05:37 UTC, Alexey-GM commented on GSON/app/src/main/java/com/example/gson/MainActivity.kt
> +    private val context: Context,
контекст тут по сути не нужен, для использования глайда можно просто передать holder.itemView

2024-11-05 05:37 UTC, Alexey-GM commented on GSON/app/src/main/java/com/example/gson/MainActivity.kt
> +data class Wrapper(
Хотелось бы чтобы адаптер, дата классы и т.д. были в отдельных файлах.

2024-11-05 05:37 UTC, Alexey-GM commented on GSON/app/src/main/java/com/example/gson/MainActivity.kt
> +        runBlocking {
в контексте обращения к сети, лучше использовать корутин скоуп с указание диспатчера IO 
сoroutineScope(Dispatchers.IO)  {
    // тут уже пилим код
}

2024-11-05 05:37 UTC, Alexey-GM commented on GSON/app/src/main/java/com/example/gson/MainActivity.kt
> +        runBlocking {
Потому что при использовании runBlocking код получается синхронным и по сути блокирует до своего выполнения все остальное, так как корутина запускается во вью потоке. Но я полагаю если сделать выполнение не последовательно а параллельно, то там возникает у вас ошибка с определением lateinit var adapter, это можно обойти отправив при определении переменной адаптер в нее пустой список и потом когда данные подгрузятся этот список обновить уведомив адаптер.

2024-11-05 05:37 UTC, Alexey-GM commented on GSON/app/src/main/java/com/example/gson/MainActivity.kt
> +        runBlocking {
почитать подробнее
https://developer.android.com/codelabs/basic-android-kotlin-compose-coroutines-kotlin-playground?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-5-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-coroutines-kotlin-playground#2
займет 15-20 минут)

2024-11-05 05:37 UTC, Alexey-GM commented on GSON/app/src/main/java/com/example/gson/MainActivity.kt
> +fun getResponse(callback: (String?) -> Unit) {
а нужен ли этот метод? Может его можно более компактно объединить с методом fetchData?

2024-11-14 16:23 UTC, De-Len commented on GSON/app/src/main/java/com/example/gson/MainActivity.kt
> +    private val context: Context,
val view = LayoutInflater.from(CONTEXT).inflate(R.layout.rview_item, parent, false)

Ниже есть такой момент. Кажется, тут без контекста не обойтись?

2024-11-14 16:24 UTC, De-Len commented on GSON/app/src/main/java/com/example/gson/MainActivity.kt
> +data class Wrapper(
Принято

2024-11-14 16:26 UTC, De-Len commented on GSON/app/src/main/java/com/example/gson/MainActivity.kt
> +fun getResponse(callback: (String?) -> Unit) {
Точно, во время разработки не заметил уже

2024-11-14 16:28 UTC, De-Len commented on GSON/app/src/main/java/com/example/gson/MainActivity.kt
> +        runBlocking {
Спасибо, это я и хотел сделать. Как я помню, вылазила какая-то ошибка. В следующий раз сделаю именно параллельно.

2025-05-26 13:22 UTC, closed without merging